### ISSUE TITLE
faviconが表示されない

### ISSUE THREAD

**Issue by norihirosunada** [norihirosunada/express#1]
# 概要
- 教科書008のstep2でfaviconを追加したのですが表示されません。
# 画面
[![Image from Gyazo](https://i.gyazo.com/702dbd206e2995b3d0d8f65649dc7d85.png)](https://gyazo.com/702dbd206e2995b3d0d8f65649dc7d85)

**Comment by kojitaniguchi** [comment]
@norihirosunada 

手元でやってみたら、うまく表示されてたから、コードには問題なさそう！
[![Image from Gyazo](https://i.gyazo.com/a1ef9647c2e6f93ce542906b160f8afb.png)](https://gyazo.com/a1ef9647c2e6f93ce542906b160f8afb)
**もしかしたら、キャッシュが邪魔してるかもだから、 スーパーリロード(`command + shift + R`)してリソースの強制読み込みを試してみてほしい！**

**Comment by norihirosunada** [comment]
スーパーリロードで行けましたー！
